# Generated by Django 5.0.6 on 2024-07-12 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_role', models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('designer', 'Designer'), ('tester', 'Tester'), ('analyst', 'Analyst')], max_length=50)),
                ('unique_key', models.CharField(max_length=6)),
            ],
        ),
    ]
