# Generated by Django 5.0.6 on 2024-07-12 06:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='actual_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
