# Generated by Django 5.0.6 on 2024-07-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_actual_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='emp_role',
            field=models.CharField(choices=[('manager', 'Manager'), ('developer', 'Developer'), ('hr', 'HR'), ('sales', 'Sales'), ('marketing', 'Marketing'), ('support', 'Support'), ('accountant', 'Accountant'), ('admin', 'Admin'), ('it_support', 'IT Support'), ('project_manager', 'Project Manager'), ('designer', 'Designer'), ('product_manager', 'Product Manager'), ('operations', 'Operations'), ('executive', 'Executive'), ('intern', 'Intern'), ('cleaner', 'Cleaner'), ('security', 'Security'), ('piun', 'Piun')], max_length=50),
        ),
    ]
