# Generated by Django 5.0.6 on 2024-07-22 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cred', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cred',
            old_name='we_password',
            new_name='web_password',
        ),
    ]
