# Generated by Django 5.0.6 on 2024-07-16 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_username', models.CharField(max_length=200)),
                ('web_password', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('unique_key', models.CharField(max_length=200)),
            ],
        ),
    ]
