# Generated by Django 5.0.6 on 2024-07-16 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=200)),
                ('admin_password', models.CharField(max_length=200)),
                ('web_username', models.CharField(max_length=200)),
                ('web_password', models.CharField(max_length=200)),
                ('updated_on', models.DateField()),
            ],
        ),
    ]
