# Generated by Django 5.0.6 on 2024-07-16 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner_credentials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownercredentials',
            name='updated_on',
            field=models.CharField(max_length=200),
        ),
    ]
