# Generated by Django 5.0.6 on 2024-07-16 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=200)),
                ('performance', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('reward', models.CharField(max_length=200)),
                ('suggestion', models.CharField(max_length=200)),
            ],
        ),
    ]
