# Generated by Django 5.0.6 on 2024-07-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=200)),
                ('salary_credited', models.CharField(max_length=200)),
                ('payment_method', models.CharField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
