# Generated by Django 5.0.6 on 2024-07-14 14:23

import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.TextField()),
                ('notice_content', tinymce.models.HTMLField()),
            ],
        ),
    ]
