# Generated by Django 5.0.6 on 2024-07-15 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collect_Assets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=200)),
                ('emp_role', models.CharField(max_length=200)),
                ('asset', models.CharField(max_length=500)),
                ('condition', models.CharField(max_length=400)),
                ('date', models.DateField()),
                ('image', models.ImageField(upload_to='asset_images/')),
            ],
        ),
    ]
