# Generated by Django 5.0.6 on 2024-07-15 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collect_assets', '0002_collectassets_delete_collect_assets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='collectassets',
            name='image',
        ),
    ]
